name: cmp-dictionary

on:
  push:
    branches: [main]
    paths:
      - "README.md"

jobs:
  doc:
    runs-on: ubuntu-latest
    name: readme to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: cmp-dictionary
          pandoc: README.md
          description: Dictionary completion source for nvim-cmp
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
