name: cmp-dictionary

on:
  push:
    branches: [main]
    paths:
      - "DOC.md"

jobs:
  doc:
    runs-on: ubuntu-latest
    name: markdown to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: cmp-dictionary
          pandoc: DOC.md
          description: Dictionary completion source for nvim-cmp
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
